const container = document.querySelector("#container");

const div1 = document.createElement("div");
const div2 = document.createElement("div");
const div3 = document.createElement("div");
const div4 = document.createElement("div");
const div5 = document.createElement("div");
const div6 = document.createElement("div");
const div7 = document.createElement("div");
const div8 = document.createElement("div");
const div9 = document.createElement("div");
const div10 = document.createElement("div");
const div11 = document.createElement("div");
const div12 = document.createElement("div");
const div13 = document.createElement("div");
const div14 = document.createElement("div");
const div15 = document.createElement("div");
const div16 = document.createElement("div");
const div17 = document.createElement("div");
const div18 = document.createElement("div");
const div19 = document.createElement("div");
const div20 = document.createElement("div");
const div21 = document.createElement("div");
const div22 = document.createElement("div");
const div23 = document.createElement("div");
const div24 = document.createElement("div");
const div25 = document.createElement("div");
const div26 = document.createElement("div");
const div27 = document.createElement("div");
const div28 = document.createElement("div");
const div29 = document.createElement("div");
const div30 = document.createElement("div");
const div31 = document.createElement("div");
const div32 = document.createElement("div");

div1.style.border = "2px dotted black";
div2.style.border = "2px solid black";
div3.style.border = "2px solid black";
div4.style.border = "2px solid black";
div5.style.border = "2px solid black";
div6.style.border = "2px solid black";
div7.style.border = "2px solid black";
div8.style.border = "2px solid black";
div9.style.border = "2px solid black";
div10.style.border = "2px solid black";
div11.style.border = "2px solid black";
div12.style.border = "2px solid black";
div13.style.border = "2px solid black";
div14.style.border = "2px solid black";
div15.style.border = "2px solid black";
div16.style.border = "2px solid black";

container.appendChild(div1);
container.appendChild(div2);
container.appendChild(div3);
container.appendChild(div4);
container.appendChild(div5);
container.appendChild(div6);
container.appendChild(div7);
container.appendChild(div8);
container.appendChild(div9);
container.appendChild(div10);
container.appendChild(div11);
container.appendChild(div12);
container.appendChild(div13);
container.appendChild(div14);
container.appendChild(div15);
container.appendChild(div16);
container.appendChild(div17);
container.appendChild(div18);
container.appendChild(div19);
container.appendChild(div20);
container.appendChild(div21);
container.appendChild(div22);
container.appendChild(div23);
container.appendChild(div24);
container.appendChild(div25);
container.appendChild(div26);
container.appendChild(div27);
container.appendChild(div28);
container.appendChild(div29);
container.appendChild(div30);
container.appendChild(div31);
container.appendChild(div32);